<?php

/** @var \Zend\Form\Form $form */
$form = $this->form;

$form->setAttribute('action', $this->url('adminaut/settings/add', [
    'module_id' => $this->moduleOption->getModuleId(),
]));
$form->setAttribute('data-doubleClick', true);
$form->prepare();

$pages = [
    [
        'title' => "Settings",
        'url' => $this->url('adminaut/settings'),
    ],
    [
        'title' => $this->moduleOption->getModuleName(),
        'url' => $this->url('adminaut/settings/list', [
            'module_id' => $this->moduleOption->getModuleId(),
        ]),
    ],
    [
        'title' => _('Add'),
    ],
];

?>
<section class="content-header">
    <h1>
        Settings <small><?php echo $this->escapeHtml($this->moduleOption->getModuleName()) ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', ['pages' => $pages]) ?>
</section>

<section class="content">
    <?php echo $this->form()->openTag($form) ?>
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate('Add record', 'adminaut') ?></h3>
                </div>
                <div class="box-body">
                    <?php echo $this->partial('adminaut/partial/messages') ?>
                    <?php echo $this->formCollection($form) ?>
                </div>
                <div class="box-footer">
                    <button type="submit" name="submit" class="btn btn-primary" value="create">
                        <?php echo $this->translate('Create', 'adminaut') ?>
                    </button>
                    <button type="submit" name="submit" class="btn btn-default" value="create-and-continue">
                        <?php echo $this->translate('Create and continue', 'adminaut') ?>
                    </button>
                    <button type="submit" name="submit" class="btn btn-default" value="create-and-new">
                        <?php echo $this->translate('Create and new', 'adminaut') ?>
                    </button>
                    <a href="<?php echo $this->url('adminaut/settings/list', ['module_id' => $this->moduleOption->getModuleId()]) ?>" class="btn btn-link">
                        <?php echo $this->translate('Back to list', 'adminaut') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>

<?php echo $this->partial('adminaut/partial/changeModal', ['formId' => $form->getName()]) ?>
